# Generated by Django 4.0.6 on 2022-07-12 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('adopted_to_job', models.DateTimeField()),
                ('salary', models.IntegerField()),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_v1.employee')),
            ],
        ),
    ]
