# Generated by Django 4.0.6 on 2022-07-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_alter_employee_boss'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='post',
            field=models.CharField(default=1, max_length=50, verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
